#!/bin/bash
RULENO=$(iptables --line-numbers -t filter -L DOCKER-USER | grep TRAEFIKJAM | awk '{ print $1 }')
if [[ -n "$RULENO" ]]; then
	iptables -t filter -D DOCKER-USER "$RULENO"
fi
if iptables -t filter -L TRAFIKJAM >& /dev/null; then
	iptables -t filter -F TRAEFIKJAM
	iptables -t filter -X TRAEFIKJAM
fi

RULENO=$(iptables --line-numbers -t filter -L INPUT | grep TRAEFIKJAM | awk '{ print $1 }')
if [[ -n "$RULENO" ]]; then
	iptables -t filter -D INPUT "$RULENO"
fi
if iptables -t filter -L TRAEFIKJAM_INPUT >& /dev/null; then
	iptables -t filter -F TRAEFIKJAM_INPUT
	iptables -t filter -X TRAEFIKJAM_INPUT
fi