#!/bin/bash
for RULENUM in $(iptables --line-numbers -t filter -L DOCKER-USER | grep traefikjam | awk '{ print $1 }' | sort -nr); do
	iptables -t filter -D DOCKER-USER "$RULENUM"
done
for RULENUM in $(iptables --line-numbers -t filter -L INPUT | grep traefikjam | awk '{ print $1 }' | sort -nr); do
        iptables -t filter -D INPUT "$RULENUM"
done