name: CI - Nightly

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run shellcheck
        run: |
          shellcheck trafficjam-functions.sh
          shellcheck -x trafficjam.sh

      - name: Install bats
        run: |
          sudo git clone --depth 1 --branch v1.8.0 https://github.com/bats-core/bats-core.git /opt/bats
          sudo /opt/bats/install.sh /usr/local
          
      - name: Run test suite
        run: bats test/test.bats